### ISSUE TITLE
Update Help Link

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/tat-addin#1]
Under `Help→ Online Help`, it currently goes to: http://tat.riverscapes.xyz/ as does, `Help -> TAT Web Site`. Please update the `Help→ Online Help` link to: http://tat.riverscapes.xyz/Help/. I will try and get the help documentation buttoned up real quick here so we can make help links from tools work.

**Comment by hensleij** [comment]
Resolved with https://github.com/Riverscapes/tat-addin/commit/e2ff6834e53e5786b7df0b379f8ef591b0c98063
