### ISSUE TITLE
ToPCAT Detrended Standard Deviation Tool not working...

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/tat-addin#4]
Note that the `Analysis -> Uncertainty Analysis-> Point Cloud Based -> ToPCAT Standard Deviation` tool is not working.  When you try to load the form, it greys itself out on the menu. Not sure if this is a simple fix or not?
![tat_topcat_detrendedstdev](https://user-images.githubusercontent.com/9723905/38401096-045fe758-3911-11e8-8a53-4c9e06c25e9e.png)

**Comment by hensleij** [comment]
Resolved with https://github.com/Riverscapes/tat-addin/commit/2983ef7e34fbc006792e555c93438ba12fd242c6
