### ISSUE TITLE
Raw Point Cloud to Shapefile - Missing Python Script

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/tat-addin#5]
It looks like there must be some file James shipped with this in the past, that didn't get put in the new tat-addin? @philipbaileynar is this an easy fix or something we need to enlist James in? Also, the warning is good, but we should update these warning dialogs and do a find and replace of 'GCD' with 'TAT'
![tat_pointcloudtoshapefile_bug](https://user-images.githubusercontent.com/9723905/38401541-8d2a47a2-3913-11e8-9c87-9bac8bb1fee1.png)

**Comment by hensleij** [comment]
In the original GCD project within the ~/Resources folder there is/was a RScripts folder this folder needs to be included in the project for this tool and other tools to work. For this tool specifically the rawPointCloudToShp.py script from this folder needs to be included.

**Comment by philipbaileynar** [comment]
@JamesSLC I've added the RScripts folder back in. However it might be in different location than before. It should just be in a folder next to the binaries called RScripts not under Resources. Please test.

**Comment by hensleij** [comment]
Resolved with https://github.com/Riverscapes/tat-addin/commit/600f9d8fad24dcb8524ba80284f7baef9b23353f
