### ISSUE TITLE
Coincident Point Tool not able to run. - Missing Python File

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/tat-addin#6]
Similar error to #5, but this for the conicdent point tool.
![tat_coincidentpointtools](https://user-images.githubusercontent.com/9723905/38402283-4c842a06-3918-11e8-895a-386c74f7379a.png)

**Comment by hensleij** [comment]
Same issue as issue #5 just need to include toPCAT_outPutToShp_OsgeoOption.py

**Comment by philipbaileynar** [comment]
@JamesSLC I've added the RScripts folder back in. However it might be in different location than before. It should just be in a folder next to the binaries called `RScripts` not under `Resources`. Please test.

**Comment by hensleij** [comment]
Resolved with https://github.com/Riverscapes/tat-addin/commit/600f9d8fad24dcb8524ba80284f7baef9b23353f
